name: Test

on:
  workflow_call:
    outputs:
      matrix:
        description: "The strategy matrix used to build images"
        value: ${{ jobs.build.outputs.matrix }}
  pull_request:
  push:
    branches: [ "latest" ]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/DockerBuild.yml

  test:
    runs-on: ubuntu-latest
    name: Test Images
    needs: build

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build.outputs.matrix) }}

    steps:
      - name: Fetch image artifact
        uses: actions/download-artifact@v4
        with:
          name: slurm-${{ matrix.slurm-version }}
          path: /tmp

      - name: Load image
        run: docker load --input /tmp/image.tar

      - name: Test container is restartable
        run: |
          image_name="ghcr.io/pitt-crc/test-env:${{ matrix.slurm-version }}"
          docker container create --name rerun_test_container $image_name
          docker container start -i rerun_test_container
          docker container start -i rerun_test_container
          docker container rm rerun_test_container

      - name: Run bats tests
        run: |
          image_name="ghcr.io/pitt-crc/test-env:${{ matrix.slurm-version }}"
          docker run  -i -v $(pwd)/tests:/tests $image_name bats /tests

 # Use this job for branch protection rules
  report-test-status:
    name: Report Status
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
      - name: Check build status
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled') }}
        run: exit 1
