name: Docker Images

on:
  pull_request:
  release:
    types: [ published ]
  push:
    branches: [ "latest" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test Images

    strategy:
      fail-fast: false
      matrix:
        slurm-tag: [ "slurm-20-02-5-1", "slurm-20-11-9-1", "slurm-22-05-2-1" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      # Extract metadata (tags and labels) for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/test-env-${{ matrix.slurm-tag }}

      # Build the image but do not publish it
      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SLURM_TAG=${{ matrix.slurm-tag }}

      - name: Test container is restartable
        run: |
          tag_array=(${{ steps.meta.outputs.tags }})
          docker container create --name rerun_test_container ${tag_array[0]}
          docker container start -i rerun_test_container
          docker container start -i rerun_test_container
          docker container rm rerun_test_container

      # Check slurm utilities all execute without error
      - name: Test slurm install
        run: |
          tag_array=(${{ steps.meta.outputs.tags }})
          docker run --rm ${tag_array[0]} sacctmgr -V
          docker run --rm ${tag_array[0]} slurmctld -V
          docker run --rm ${tag_array[0]} slurmdbd -V

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish built image
        if: github.event_name == 'release'
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SLURM_TAG=${{ matrix.slurm-tag }}

  # This is a dummy job used to facilitate branch protections
  build-successful:
    needs: [ build ]
    runs-on: ubuntu-latest
    name: Builds Were Successful

    steps:
      - name: Mark as completed
        run: echo "The builds were successful"
