name: Docker

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:    
    strategy:
      fail-fast: false
      matrix:
        rhel-tag: [ "ubi8" ]
        slurm-tag: [ "slurm-20-02-5-1", "slurm-20-11-9-1", "slurm-22-05-2-1" ]

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write # This is used to complete the identity challenge

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install the cosign tool except
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        uses: sigstore/cosign-installer@7e0881f8fe90b25e305bbf0309761e9314607e25
        with:
          cosign-release: 'v1.9.0'

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into registry ghcr.io
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/slurm-env-${{ matrix.rhel-tag }}-${{ matrix.slurm-tag }}

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build image for RHEL ${{ matrix.rhel-tag }} and Slurm ${{ matrix.slurm-tag }}
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SLURM_TAG=${{ matrix.slurm-tag }}
            RHEL_TAG=${{ matrix.rhel-tag }}
