name: Publish Docker Images

on:
  push:
  release:
    types: [ "released" ]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/DockerTest.yml

  publish:
    runs-on: ubuntu-latest
    name: Publish Docker Images
    needs: [ build ]

    strategy:
      fail-fast: false
      matrix:
        slurm-tag: [ "slurm-20-02-5-1", "slurm-20-11-9-1", "slurm-22-05-2-1" ]

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download images from GitHub artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.slurm-tag }}

      - name: Load image
        run: |
          docker load --input ${{ matrix.slurm-tag }}.tar
          docker image ls -a

      - name: Login to GitHub Container Registry
        if: github.event_name == 'release'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Publish built image
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
      #     build-args: SLURM_TAG=${{ matrix.slurm-tag }}
#