name: Delete Old Docker Images

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

jobs:
  delete-old:
    needs: [ define-build-options, publish ]
    runs-on: ubuntu-latest
    name: Delete Old Images

    steps:
      # Clean up all versions that do not start with a 'v'
      # This should be equivalent to all versions except releases
      - name: Delete old packages
        uses: SmartsquareGmbH/delete-old-packages@v0.5.0
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          organization: my-organization
          type: container
          version-pattern: "^[^vV].*"
          keep: 3
          dry-run: true