name: Delete Old Docker Images

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

jobs:
  delete-old:
    runs-on: ubuntu-latest
    name: Delete Old Images

    steps:
      # Clean up all versions that do not start with a 'v'
      # This should be equivalent to all versions except releases
      - name: Delete old packages
        uses: SmartsquareGmbH/delete-old-packages@v0.5.0
        with:
          token: ${{ github.token }}
          organization:  pitt-crc
          repo: ${{ secrets.repository }}
          type: container
          version-pattern: "^[^vV].*"
          keep: 3
          dry-run: true
          names: |
            - test-env-rocky8-slurm-20-11-9-1-python36
            - test-env-rocky8-slurm-20-02-5-1-python39
            - test-env-rocky8-slurm-20-02-5-1-python36
            - test-env-rocky8-slurm-22-05-2-1-python36
            - test-env-rocky8-slurm-20-11-9-1-python38
            - test-env-rocky8-slurm-20-02-5-1-python38
            - test-env-rocky8-slurm-22-05-2-1-python39
            - test-env-rocky8-slurm-22-05-2-1-python38
            - test-env-rocky8-slurm-20-11-9-1-python39
