name: Build

on:
  workflow_call:
    outputs:
      matrix:
        description: "The first output string"
        value: ${{ jobs.matrix.outputs.matrix }}

jobs:
  matrix:
    name: Define Matrix
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.load-matrix.outputs.matrix }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Load matrix
        id: load-matrix
        uses: ActionsTools/read-json-action@main
        with:
          file_path: ".github/workflows/matrix.json"

  build:
    name: Build Images
    runs-on: ubuntu-latest
    needs: matrix

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}

    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          tags: ${{ matrix.image-tags }}
          outputs: type=docker,dest=/tmp/image.tar
          build-args: SLURM_VERSION=${{ matrix.slurm-version }}

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: slurm-${{ matrix.slurm-version }}
          path: /tmp/image.tar
