name: Publish Docker Images

on:
  pull_request:
  release:
    types: [ "released" ]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/test-env

jobs:
  build:
    name: Build Images
    uses: ./.github/workflows/DockerTest.yml

  publish:
    runs-on: ubuntu-latest
    name: Publish Images
    needs: [ build ]

    strategy:
      fail-fast: false
      matrix:
        include:
          - slurm-version: 20.02.5.1
            tags: $IMAGE_NAME:20.02.5.1

          - slurm-version: 20.11.9.1
            tags: $IMAGE_NAME:20.11.9.1

          - slurm-version: 22.05.2.1
            tags: $IMAGE_NAME:22.05.2.1,$IMAGE_NAME:latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ matrix.tags }}
          build-args: SLURM_VERSION=${{ matrix.slurm-version }}
