name: Build Images

on:
  # These triggers will build and test the image(s)
  workflow_dispatch:
  pull_request:

  # These triggers will build, test, and publish the image(s)
  release:
    types: [ published ]
  push:

jobs:
  define-build-options:
    name: Define Build Options
    uses: ./.github/workflows/matrix.yml

  build-images:
    needs: [ define-build-options ]
    runs-on: ubuntu-latest
    name: Build Docker Image

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.define-build-options.outputs.matrix) }}

    steps:
      - name: Generate image name
        id: image-name
        run: |
          NAME=test-env-rocky${{ matrix.rocky-tag }}-${{ matrix.slurm-tag }}-${{ matrix.python-tag }}
          echo ::set-output name=name::$NAME

