name: Delete Old Docker Images

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

jobs:
  delete-old:
    runs-on: ubuntu-latest
    name: Delete Old Images

    steps:
      - uses: actions/delete-package-versions@v3
        with: 
          package-name: 'test-package'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: "true"
