name: Publish Docker Images

on:
  pull_request:
  release:
    types: [ published ]
  push:
    branches: [ "latest" ]
  schedule:
    - cron: '0 0 * * 0'  # every week on sunday

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test Images

    strategy:
      fail-fast: false
      matrix:
        slurm-tag: [ "slurm-20-02-5-1", "slurm-20-11-9-1", "slurm-22-05-2-1" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      # Define the image name for use by other steps
      - name: Define image name
        id: image-name
        run: |
          NAME=test-env-${{ matrix.slurm-tag }}
          echo ::set-output name=name::$NAME

      # Extract metadata (tags and labels) for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ steps.image-name.outputs.name }}

      # Build the image but do not publish it
      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SLURM_TAG=${{ matrix.slurm-tag }}

      # Make sure sacctmgr executes
      - name: Test slurm install
        run: docker run --rm ${{ steps.meta.outputs.tags }} sacctmgr --version

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish built image
        uses: docker/build-push-action@v3
        if: (github.ref == 'refs/heads/latest' && github.event_name == 'push') || (github.event_name == 'release')
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SLURM_TAG=${{ matrix.slurm-tag }}

      - name: Delete old images
        uses: actions/delete-package-versions@v3
        with:
          package-name: ${{ steps.image-name.outputs.name }}
          min-versions-to-keep: 5
          ignore-versions: '^(v).*'