name: Deploy Docker Images

on:
  workflow_dispatch:
  push:
    branches: [ "latest" ]

env:
  REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Setup matrix combinations
        id: setup-matrix-combinations
        run: |
          MATRIX='
              {"rocky-tag": "8", "slurm-tag": "slurm-20-02-5-1", "python-tag": "python36"},
              {"rocky-tag": "8", "slurm-tag": "slurm-20-11-9-1", "python-tag": "python38"},
              {"rocky-tag": "8", "slurm-tag": "slurm-22-05-2-1", "python-tag": "python39"},
              {"rocky-tag": "8", "slurm-tag": "slurm-20-02-5-1", "python-tag": "python36"},
              {"rocky-tag": "8", "slurm-tag": "slurm-20-11-9-1", "python-tag": "python38"},
              {"rocky-tag": "8", "slurm-tag": "slurm-22-05-2-1", "python-tag": "python39"},
              {"rocky-tag": "8", "slurm-tag": "slurm-20-02-5-1", "python-tag": "python36"},
              {"rocky-tag": "8", "slurm-tag": "slurm-20-11-9-1", "python-tag": "python38"},
              {"rocky-tag": "8", "slurm-tag": "slurm-22-05-2-1", "python-tag": "python39"},
          '

          echo ::set-output name=matrix-combinations::{\"include\":[$MATRIX]}

    outputs:
      matrix-combinations: ${{ steps.setup-matrix-combinations.outputs.matrix-combinations }}

  build:
    runs-on: ubuntu-latest
    name: Build Docker Images
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix-combinations) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install the cosign tool to sign and verify container images
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.9.0'

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/test-env-${{ matrix.rocky-tag }}-${{ matrix.slurm-tag }}-${{ matrix.python-tag }}

      # Build the image but do not publish it
      # https://github.com/docker/build-push-action
      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SLURM_TAG=${{ matrix.slurm-tag }}
            ROCKY_TAG=${{ matrix.rocky-tag }}
            PYTHON_TAG=${{ matrix.python-tag }}

      # Make sure sacctmgr executes
      - name: Test slurm install
        run: |
          docker run --rm ${{ steps.meta.outputs.tags }} sacctmgr --version

  publish:
    needs: build
    runs-on: ubuntu-latest
    name: Publish Docker Images
    permissions:
      contents: read
      packages: write
      id-token: write # This is used to complete the identity challenge

    strategy:
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix-combinations) }}

    steps:
      # Build and push the image the container registry
      # This will use a cached copy of the previous build
      - name: Publish built image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SLURM_TAG=${{ matrix.slurm-tag }}
            ROCKY_TAG=${{ matrix.rocky-tag }}
            PYTHON_TAG=${{ matrix.python-tag }}
