name: Test Docker Images

on:
  workflow_call:
  pull_request:
  push:
    branches: [ "latest" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test Images

    strategy:
      fail-fast: false
      matrix:
        slurm-tag: [ "slurm-20-02-5-1", "slurm-20-11-9-1", "slurm-22-05-2-1" ]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          load: true
          tags: test-image
          labels: ${{ steps.meta.outputs.labels }}
          build-args: SLURM_TAG=${{ matrix.slurm-tag }}

      - name: Run tests
        run: |
          sudo apt install bats -y
          bats tests

  # This is a dummy job used to facilitate branch protections
  build-successful:
    if: ${{ always() }}
    name: Report Status
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Report status
        shell: bash
        run: |
          if [[ success == ${{ needs.build.result }} ]]
          then
            echo "Builds were successful"
          else
            echo "One or more matrix jobs failed."
            false
          fi
