name: Test Docker Images

on:
  workflow_call:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test Images

    strategy:
      fail-fast: false
      matrix:
        include:
          - slurm-version: "20.02.5.1"
            tags: "20.02.5.1"
          - slurm-version: "20.11.9.1"
            tags: "20.11.9.1"
          - slurm-version: "22.05.2.1"
            tags: "22.05.2.1", "latest"

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          load: true
          tags: ${{ matrix.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: SLURM_VERSION=${{ matrix.slurm-version }}

      - name: Test container is restartable
        run: |
          docker container create --name rerun_test_container test-image
          docker container start -i rerun_test_container
          docker container start -i rerun_test_container
          docker container rm rerun_test_container

      - name: Run bats tests
        run: docker run  -i -v $(pwd)/tests:/tests test-image bats /tests

  # This is a dummy job used to facilitate branch protections
  build-successful:
    if: ${{ always() }}
    name: Report Status
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Report status
        shell: bash
        run: |
          if [[ success == ${{ needs.build.result }} ]]
          then
            echo "Builds were successful"
          else
            echo "One or more matrix jobs failed."
            false
          fi
