name: Build Docker Image

on:
  workflow_call:
    outputs:
      matrix:
        description: "A JSON encoded strategy metrix for build jobs"
        value: ${{ jobs.define-build-options.outputs.matrix }}

jobs:
  define-build-options:
    runs-on: ubuntu-latest
    name: Define Build Options

    outputs:
      matrix: ${{ steps.define-matrix.outputs.matrix }}

    steps:
      - name: Define matrix options
        id: define-matrix
        run: |
          MATRIX="{
            "rocky-tag": [ "8" ], 
            "slurm-tag": [ "slurm-20-02-5-1", "slurm-20-11-9-1", "slurm-22-05-2-1" ], 
            "python-tag":[ "python36", "python38", "python39" ]
          }"
          
          echo "::set-output name=matrix::$MATRIX"
