name: Build Docker Image

on:
  workflow_call:

jobs:
  define-build-options:
    runs-on: ubuntu-latest
    name: Define Build Options

    steps:
      - name: Define matrix options
        id: define-matrix
        run: |
          MATRIX='{
            "rocky-tag": [ "8" ], 
            "slurm-tag": [ "slurm-20-02-5-1", "slurm-20-11-9-1", "slurm-22-05-2-1" ], 
            "python-tag":[ "python36", "python38", "python39" ]
          }'
          
          echo ::set-output name=matrix::$MATRIX}
    outputs:
      matrix: ${{ steps.define-matrix.outputs.matrix }}