name: Publish Docker Images

on:
  workflow_dispatch:
  push:
    branches: [ "latest" ]
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/build_image.yml@latest

  publish:
    runs-on: ubuntu-latest
    name: Publish Docker Images
    permissions:
      contents: read
      packages: write
      id-token: write # This is used to complete the identity challenge

    strategy:
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix-combinations) }}

    steps:
      # Build and push the image the container registry
      # This will use a cached copy of the previous build
      - name: Publish built image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SLURM_TAG=${{ matrix.slurm-tag }}
            ROCKY_TAG=${{ matrix.rocky-tag }}
            PYTHON_TAG=${{ matrix.python-tag }}
