name: 🎯 Release

on:
  release:
    types: [ "released" ]

jobs:
  matrix:
    name: Matrix
    uses: ./.github/workflows/Matrix.yml

  build:
    name: Build
    needs: [ matrix ]
    uses: ./.github/workflows/Build.yml
    with:
      matrix: ${{ needs.matrix.outputs.matrix }}

  test:
    name: Test
    needs: [ matrix, build ]
    uses: ./.github/workflows/Test.yml
    with:
      matrix: ${{ needs.matrix.outputs.matrix }}

  publish:
    name: Publish
    needs: [ matrix, build, test ]
    uses: ./.github/workflows/Publish.yml
    with:
      matrix: ${{ needs.matrix.outputs.matrix }}
